// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Models;

namespace Repository.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Repository.Models.Categoria", b =>
                {
                    b.Property<int>("idCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_CATEGORIA")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnName("DESCRICAO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnName("NOME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCategoria");

                    b.ToTable("CATEGORIAS");
                });

            modelBuilder.Entity("Repository.Models.Enunciado", b =>
                {
                    b.Property<int>("idEnunciado")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_ENUNCIADO")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoriaidCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnName("DESCRICAO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idCategoria")
                        .HasColumnName("ID_CATEGORIA")
                        .HasColumnType("int");

                    b.HasKey("idEnunciado");

                    b.HasIndex("CategoriaidCategoria");

                    b.ToTable("ENUNCIADOS");
                });

            modelBuilder.Entity("Repository.Models.Opcao", b =>
                {
                    b.Property<int>("idOpcao")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_OPCAO")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoriaidCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnName("DESCRICAO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpcaoVerdadeiraPara")
                        .HasColumnName("OPCAO_VERDADEIRA_PARA")
                        .HasColumnType("int");

                    b.Property<int>("idCategoria")
                        .HasColumnName("ID_CATEGORIA")
                        .HasColumnType("int");

                    b.HasKey("idOpcao");

                    b.HasIndex("CategoriaidCategoria");

                    b.ToTable("OPCOES");
                });

            modelBuilder.Entity("Repository.Models.Partida", b =>
                {
                    b.Property<int>("idPartida")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_PROJECT_USER")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataHora")
                        .HasColumnName("DATA_HORA")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StatusidStatus")
                        .HasColumnType("int");

                    b.Property<int>("idStatus")
                        .HasColumnName("ID_STATUS")
                        .HasColumnType("int");

                    b.HasKey("idPartida");

                    b.HasIndex("StatusidStatus");

                    b.ToTable("PARTIDAS");
                });

            modelBuilder.Entity("Repository.Models.Pergunta", b =>
                {
                    b.Property<int>("idPergunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_PERGUNTA")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EnunciadoidEnunciado")
                        .HasColumnType("int");

                    b.Property<int?>("OpcaoidOpcao")
                        .HasColumnType("int");

                    b.Property<int>("idEnunciado")
                        .HasColumnName("ID_ENUNCIADO")
                        .HasColumnType("int");

                    b.Property<int>("idOpcao")
                        .HasColumnName("ID_OPCAO")
                        .HasColumnType("int");

                    b.HasKey("idPergunta");

                    b.HasIndex("EnunciadoidEnunciado");

                    b.HasIndex("OpcaoidOpcao");

                    b.ToTable("PERGUNTAS");
                });

            modelBuilder.Entity("Repository.Models.Placar", b =>
                {
                    b.Property<int>("idPlacar")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_PLACAR")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Porntuacao")
                        .HasColumnName("PONTUACAO")
                        .HasColumnType("int");

                    b.Property<int>("QtdTapaDado")
                        .HasColumnName("QTD_TAPA_DADO")
                        .HasColumnType("int");

                    b.Property<int>("QtdTapaRecebido")
                        .HasColumnName("QTD_TAPA_RECEBIDO")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioidUsuario")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnName("ID_USUARIO")
                        .HasColumnType("int");

                    b.HasKey("idPlacar");

                    b.HasIndex("UsuarioidUsuario");

                    b.ToTable("PLACARES");
                });

            modelBuilder.Entity("Repository.Models.Rodada", b =>
                {
                    b.Property<int>("idRodada")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_RODADA")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PartidaidPartida")
                        .HasColumnType("int");

                    b.Property<int?>("PerguntaidPergunta")
                        .HasColumnType("int");

                    b.Property<int>("idPartida")
                        .HasColumnName("ID_PARTIDA")
                        .HasColumnType("int");

                    b.Property<int>("idPergunta")
                        .HasColumnName("ID_PERGUNTA")
                        .HasColumnType("int");

                    b.HasKey("idRodada");

                    b.HasIndex("PartidaidPartida");

                    b.HasIndex("PerguntaidPergunta");

                    b.ToTable("RODADAS");
                });

            modelBuilder.Entity("Repository.Models.Sessao", b =>
                {
                    b.Property<int>("idSessao")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_SESSAO")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PartidaidPartida")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioidUsuario")
                        .HasColumnType("int");

                    b.Property<int>("idPartida")
                        .HasColumnName("ID_PARTIDA")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnName("ID_USUARIO")
                        .HasColumnType("int");

                    b.HasKey("idSessao");

                    b.HasIndex("PartidaidPartida");

                    b.HasIndex("UsuarioidUsuario");

                    b.ToTable("SESSOES");
                });

            modelBuilder.Entity("Repository.Models.Status", b =>
                {
                    b.Property<int>("idStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_STATUS")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativa")
                        .HasColumnName("ATIVA")
                        .HasColumnType("bit");

                    b.Property<int?>("PlacaridPlacar")
                        .HasColumnType("int");

                    b.Property<int>("idPlacar")
                        .HasColumnName("ID_PLACAR")
                        .HasColumnType("int");

                    b.HasKey("idStatus");

                    b.HasIndex("PlacaridPlacar");

                    b.ToTable("STATUS");
                });

            modelBuilder.Entity("Repository.Models.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_USUARIO")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnName("NOME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnName("SENHA")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idUsuario");

                    b.ToTable("USUARIOS");
                });

            modelBuilder.Entity("Repository.Models.Enunciado", b =>
                {
                    b.HasOne("Repository.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaidCategoria");
                });

            modelBuilder.Entity("Repository.Models.Opcao", b =>
                {
                    b.HasOne("Repository.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaidCategoria");
                });

            modelBuilder.Entity("Repository.Models.Partida", b =>
                {
                    b.HasOne("Repository.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusidStatus");
                });

            modelBuilder.Entity("Repository.Models.Pergunta", b =>
                {
                    b.HasOne("Repository.Models.Enunciado", "Enunciado")
                        .WithMany()
                        .HasForeignKey("EnunciadoidEnunciado");

                    b.HasOne("Repository.Models.Opcao", "Opcao")
                        .WithMany()
                        .HasForeignKey("OpcaoidOpcao");
                });

            modelBuilder.Entity("Repository.Models.Placar", b =>
                {
                    b.HasOne("Repository.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioidUsuario");
                });

            modelBuilder.Entity("Repository.Models.Rodada", b =>
                {
                    b.HasOne("Repository.Models.Partida", "Partida")
                        .WithMany()
                        .HasForeignKey("PartidaidPartida");

                    b.HasOne("Repository.Models.Pergunta", "Pergunta")
                        .WithMany()
                        .HasForeignKey("PerguntaidPergunta");
                });

            modelBuilder.Entity("Repository.Models.Sessao", b =>
                {
                    b.HasOne("Repository.Models.Partida", "Partida")
                        .WithMany()
                        .HasForeignKey("PartidaidPartida");

                    b.HasOne("Repository.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioidUsuario");
                });

            modelBuilder.Entity("Repository.Models.Status", b =>
                {
                    b.HasOne("Repository.Models.Placar", "Placar")
                        .WithMany()
                        .HasForeignKey("PlacaridPlacar");
                });
#pragma warning restore 612, 618
        }
    }
}
